name: Build Dissertation

on: 
    workflow_dispatch:
    push:
      branches: ['main']  

jobs:
  build: 
    name : Build 🔨
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: docs/dissertation/l4proj.tex 
          extra_fonts: |
            docs/dissertation/fonts/*.otf 
            docs/dissertation/fonts/*.ttf 
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: dissertation_michal_wozniak.pdf
